import { Router } from 'express';
import { generateQuestions } from '../controllers/generateController.js';

/**
 * Generate Routes — Handles AI question generation using Google Gemini.
 *
 * Routes:
 *   POST /api/vapi/generate — Takes a domain, difficulty, and topics,
 *                             and returns a list of interview questions
 *                             generated by the Gemini AI model.
 *
 * This route is called when the user starts a new interview.
 * The generated questions are then saved to the interview record in MongoDB.
 */
const router = Router();

router.post('/', generateQuestions); // Generate interview questions via Gemini AI

export default router;
