import { Link, Navigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { Mic, BarChart2, Clock, Zap, ArrowRight } from 'lucide-react';

export default function HomePage() {
  const { user, loading } = useAuth();

  if (loading) return null;
  if (user) return <Navigate to="/dashboard" replace />;

  return (
    <main className="min-h-screen bg-white">
      {/* Nav */}
      <nav className="fixed top-0 inset-x-0 z-50 bg-white/80 backdrop-blur border-b border-surface-200">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <span className="font-semibold text-lg tracking-tight text-ink">
            Vox<span className="text-brand-600">Tutor</span>
          </span>
          <div className="flex items-center gap-3">
            <Link to="/sign-in" className="btn-ghost">Sign in</Link>
            <Link to="/sign-up" className="btn-primary">Get started</Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-32 pb-24 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 badge-brand mb-6 px-4 py-1.5 text-sm">
            <Zap size={14} />
            AI-powered voice interviews
          </div>

          <h1 className="text-5xl md:text-6xl font-bold text-ink leading-tight mb-6 tracking-tight">
            Interview practice that
            <br />
            <span className="text-brand-600">actually talks back.</span>
          </h1>

          <p className="text-xl text-ink-secondary max-w-2xl mx-auto mb-10 leading-relaxed">
            VoxTutor runs real voice interviews tailored to your domain and experience level.
            Adaptive follow-ups. Structured feedback. All in your browser.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link to="/sign-up" className="btn-primary btn-lg">
              Start practicing free <ArrowRight size={18} />
            </Link>
            <Link to="/sign-in" className="btn-secondary btn-lg">
              Sign in
            </Link>
          </div>

          {/* Waveform visual */}
          <div className="mt-16 flex items-end justify-center gap-1.5 h-16">
            {[12, 20, 32, 44, 36, 24, 40, 48, 28, 16, 32, 40, 24, 16].map((h, i) => (
              <div
                key={i}
                className="wave-bar"
                style={{ height: h, animationDelay: `${i * 0.08}s` }}
              />
            ))}
          </div>
          <p className="text-sm text-ink-muted mt-4">Live voice interview in progress</p>
        </div>
      </section>

      {/* Features */}
      <section className="py-20 px-6 bg-surface-50 border-y border-surface-200">
        <div className="max-w-5xl mx-auto">
          <p className="section-label text-center mb-12">What VoxTutor does</p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              {
                icon: Mic,
                title: 'Voice Interviews',
                desc: 'A real AI voice agent conducts the interview — speaks questions, listens to your answers.',
              },
              {
                icon: Zap,
                title: 'Adaptive Questions',
                desc: 'Questions are generated by Gemini AI for your exact domain, level and topics.',
              },
              {
                icon: BarChart2,
                title: 'Feedback Reports',
                desc: 'Scored across 4 categories with strengths, improvements, and next steps.',
              },
              {
                icon: Clock,
                title: 'Interview History',
                desc: 'Every session is saved. Track your progress and re-read past feedback anytime.',
              },
            ].map(({ icon: Icon, title, desc }) => (
              <div key={title} className="card p-6">
                <div className="w-10 h-10 rounded-xl bg-brand-50 flex items-center justify-center mb-4">
                  <Icon size={20} className="text-brand-600" />
                </div>
                <h3 className="font-semibold text-ink mb-2">{title}</h3>
                <p className="text-sm text-ink-secondary leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Domains */}
      <section className="py-20 px-6">
        <div className="max-w-5xl mx-auto">
          <p className="section-label text-center mb-3">Domains covered</p>
          <h2 className="text-3xl font-bold text-center text-ink mb-12">Practice for any role</h2>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {[
              { icon: '💻', label: 'Software Engineering' },
              { icon: '📈', label: 'Finance & Banking' },
              { icon: '🎯', label: 'Marketing & Brand' },
              { icon: '🚀', label: 'Product Management' },
              { icon: '🤖', label: 'Data Science & AI' },
              { icon: '🏢', label: 'Management Consulting' },
            ].map(d => (
              <div key={d.label} className="card p-5 flex items-center gap-3">
                <span className="text-2xl">{d.icon}</span>
                <span className="font-medium text-ink text-sm">{d.label}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-6 bg-brand-600">
        <div className="max-w-2xl mx-auto text-center">
          <h2 className="text-3xl font-bold text-white mb-4">Ready to practice?</h2>
          <p className="text-brand-200 mb-8 text-lg">No credit card. No setup. Just open and interview.</p>
          <Link to="/sign-up" className="inline-flex items-center gap-2 bg-white text-brand-700 font-semibold px-8 py-4 rounded-2xl hover:bg-brand-50 transition-colors text-base">
            Create free account <ArrowRight size={18} />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 px-6 border-t border-surface-200 text-center">
        <p className="text-sm text-ink-muted">
          © 2025 VoxTutor · Built with Vapi + Gemini + Firebase
        </p>
      </footer>
    </main>
  );
}
