import mongoose from 'mongoose';

/**
 * Interview — Stores one mock interview session.
 *
 * Fields:
 *   userId      — Firebase UID of the person who did this interview
 *   domain      — The topic area (e.g. "frontend", "dsa")
 *   domainLabel — Human-readable label (e.g. "Frontend Development")
 *   domainIcon  — Emoji icon for the domain (e.g. "⚛️")
 *   difficulty  — Experience level: "entry", "mid", or "senior"
 *   duration    — How long the interview lasts in minutes (e.g. 20)
 *   questions   — The list of interview questions generated by Gemini
 *   status      — Current state of the interview: pending → active → completed
 *   transcript  — Array of {role, content, timestamp} for every spoken line
 *   completedAt — ISO timestamp when the interview ended (null if ongoing)
 */

// A single line in the transcript (one person's turn speaking)
const transcriptEntrySchema = new mongoose.Schema({
  role:      { type: String, enum: ['interviewer', 'user'], required: true },
  content:   { type: String, required: true },
  timestamp: { type: String, required: true },
}, { _id: false }); // _id: false because these are sub-documents, not top-level records

// The main interview document
const interviewSchema = new mongoose.Schema({
  userId:      { type: String, required: true, index: true },
  domain:      { type: String, required: true },
  domainLabel: { type: String, required: true },
  domainIcon:  { type: String, required: true },
  difficulty:  { type: String, enum: ['entry', 'mid', 'senior'], required: true },
  duration:    { type: Number, required: true },
  questions:   [{ type: String }],
  status:      { type: String, enum: ['pending', 'active', 'completed'], default: 'pending' },
  transcript:  [transcriptEntrySchema],
  completedAt: { type: String, default: null },
}, { timestamps: true });

export default mongoose.model('Interview', interviewSchema);
